development:
  php:
    name: php
    file_extensions:
      - php
    global_namespace:
      name: \
    namespace_separator: \
    superglobals:
      - GLOBALS
      - _POST
      - _GET
      - _REQUEST
      - _SERVER
      - FILES
      - _SESSION
      - _ENV
      - _COOKIE
    primitive_types:
      - boolean
      - bool
      - integer
      - int
      - float
      - double
      - string
      - array
      - object
      - resource
      - NULL
      - null
      - mixed
      - number
      - callback
      - callable
      - void
    magic_constants:
      - __LINE__
      - __FILE__
      - __DIR__
      - __FUNCTION__
      - __CLASS__
      - __TRAIT__
      - __METHOD__
      - __NAMESPACE__
    instance_property: this
    self_property: self
    parent_property: parent
    static_property: static
